on:
  push:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install ghstats from crates.io
        uses: baptiste0928/cargo-install@v2
        with:
          crate: ghstats 

      - name: Generate README
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_LOGIN: ${{ github.repository_owner }}
        run: |
          ghstats README.template > README.md

      - name: Commit changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "chore: update counters"
          default_author: user_info
          committer_name: GitHub Actions
          committer_email: 41898282+github-actions[bot]@users.noreply.github.com
